# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/KalmanUpdateHLS_IP/KalmanUpdateHLS_IP.xci
# IP: The module: 'KalmanUpdateHLS_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/KalmanUpdateHLS_IP/constraints/KalmanUpdateHLS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'KalmanUpdateHLS_IP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/KalmanUpdateHLS_IP/KalmanUpdateHLS_IP.xci
# IP: The module: 'KalmanUpdateHLS_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/KalmanUpdateHLS_IP/constraints/KalmanUpdateHLS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'KalmanUpdateHLS_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
