# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku115-flvb1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.cache/wt [current_project]
set_property parent.project_path /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/updater/firmware/cgn/HLS_IP_320MHz_KU115 [current_project]
set_property ip_output_repo /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ipbus_pcie/firmware/hdl/tx_dpram.v
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ipbus_pcie/firmware/hdl/ClockDomainCross.v
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ipbus_pcie/firmware/hdl/buffer_trans_if.v
}
read_vhdl -library xil_defaultlib {
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/top/firmware/hdl/top_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common/firmware/hdl/math_real.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common/firmware/hdl/numeric_tschuh.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common/firmware/hdl/config.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common/firmware/hdl/xml_utilities.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common/firmware/hdl/utilities.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common/firmware/hdl/others.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common_mp7/firmware/hdl/FunkyMiniBus.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common_mp7/firmware/hdl/GenRegister.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common_mp7/firmware/hdl/GenRomClocked.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common_mp7/firmware/hdl/GenPromClocked.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/l1tf/common_mp7/firmware/hdl/IPbusToFunkyMiniBus.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/KFstates.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/DRstates.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/Stubs.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/LinkMapping.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/AddressBookRam.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/DrStateRAM.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/LinkFormatter.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/ProtoStateCreator.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/StateFilter.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/StateSelection.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/StateAccumulator.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/StubRam.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/KfStateRAM.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/StateStubAssociation.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/KalmanWorkerCallHLS.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/framework/firmware/hdl/KalmanTop.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/kf/top/firmware/hdl/payload_KalmanFilter.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_package.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_fabric_sel.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_v.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/emp_data_types.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/boards/mpultra/firmware/hdl/emp_slim_top_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/framework/firmware/hdl/emp_framework_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/framework/firmware/hdl/emp_device_types.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/mp7_adapter/firmware/hdl/top_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/mp7_adapter/firmware/hdl/mp7_top_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/mp7_adapter/firmware/hdl/mp7_brd_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/utils/firmware/hdl/ipbus_decode_emp_slim_design.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_dc_node.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_dc_fabric_sel.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ttc/firmware/hdl/mp7_ttc_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/ipbus_decode_emp_chan_buffer.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/drp_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_drp_bridge.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_util/firmware/hdl/del_array.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/emp_chan_buffer.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_links/firmware/hdl/common/drp_mux.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/bunch_ctr.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/syncreg_r.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/syncreg_w.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_syncreg_v.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_datapath/firmware/hdl/align_mon.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/ipbus_decode_emp_region.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/emp_region.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/freq_ctr_div.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_datapath/firmware/hdl/region_info.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/ipbus_decode_emp_datapath.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/datapath/firmware/hdl/emp_datapath.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/tmt_sync.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ported_sdpram72.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/ipbus_decode_state_history.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/state_history.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/ttc_history_new.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/ttc_cmd_ctrs.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/freq_ctr.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/ttc_decoder.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/ttc_ctrs.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/rng_n1024_r32_t5_k32_s1c48.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/rng_wrapper.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/l1a_gen.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ttc/firmware/hdl/emp_ttc_cmd.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/mp7/components/mp7_ttc/firmware/hdl/ipbus_decode_mp7_ttc.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ttc/firmware/hdl/us/emp_ttc_clocks.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ttc/firmware/hdl/emp_ttc.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ctrl/firmware/hdl/ipbus_decode_emp_ctrl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ctrl/firmware/hdl/board_const_reg_legacy.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/ctrl/firmware/hdl/emp_ctrl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/info/firmware/hdl/emp_info.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_cfg.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_sm.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_if.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/trans_arb.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_txtransactor_if_simple.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_tx_mux.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_status_buffer.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxtransactor_if_simple.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_shim.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_mux.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rarp_block.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_packet_parser.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_ipaddr_block.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_tx.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_rx.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_do_rx_reset.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_clock_crossing_if.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_byte_sum.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_status.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_resend.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_ping.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_payload.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_arp.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_buffer_selector.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_if_flat.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/pcie_dma/firmware/hdl/pcie_int_gen_msix.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/pcie_dma/firmware/hdl/pcie_decl.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/pcie_dma/firmware/hdl/pcie_dma_if.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/utils/firmware/hdl/us/emp_oscclk.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/utils/firmware/hdl/us/emp_clocks.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/utils/firmware/hdl/emp_slim_infra.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/components/utils/firmware/hdl/emp_slim_top.vhd
  /home/mghorbani/workspace/kf_prj/kf-hls-work/src/emp-fwk/boards/mpultra/firmware/hdl/emp_device_decl.vhd
}
read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/KalmanUpdateHLS_IP/KalmanUpdateHLS_IP.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/KalmanUpdateHLS_IP/constraints/KalmanUpdateHLS_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/RAM_64x22/RAM_64x22.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/RAM_64x22/RAM_64x22_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/RAM_512x72/RAM_512x72.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/RAM_512x72/RAM_512x72_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/RAM_512x36/RAM_512x36.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/RAM_512x36/RAM_512x36_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc]

read_ip -quiet /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/xdma_0.xci
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie3_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie3_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/ip_0/source/xdma_0_pcie3_ip-PCIE_X0Y5.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/ip_0/synth/xdma_0_pcie3_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/ip_1/xdma_v4_1_1_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/ip_2/xdma_v4_1_1_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/xdma_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/source/xdma_0_pcie3_us_ip.xdc]
set_property used_in_implementation false [get_files -all /home/mghorbani/workspace/kf_prj/kf-hls-work/proj/kf-hls/top/top.srcs/sources_1/ip/xdma_0/synth/xdma_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xcku115-flvb1760-2-e -flatten_hierarchy none -directive AreaOptimized_high -control_set_opt_threshold 1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
